name: Update

on:
  push:
    branches: 
      - master
  schedule:
    - cron: "0 0 1 * *"

jobs:
  dns:
    name: 90DNS
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Create local changes
      run: |
        wget https://gitlab.com/a/90dns/-/raw/master/dnsmasq/dnsmasq.conf -O /tmp/dnsmasq.conf
        sed -i '/^interface.*/d' /tmp/dnsmasq.conf
        sed -i '1i\# > 90DNS'  /tmp/dnsmasq.conf
        sed -i 's/address=\//DOMAIN,/g' /tmp/dnsmasq.conf
        sed -i 's/DOMAIN,\./DOMAIN-SUFFIX,/g' /tmp/dnsmasq.conf
        sed -i 's/\/127.0.0.1/,REJECT/g' /tmp/dnsmasq.conf
        sed -i 's/\/[0-9].*/,DIRECT/g' /tmp/dnsmasq.conf
        cat /tmp/dnsmasq.conf > ./Clash/90dns.yml
    - uses: autosuite/autocommit@master
      with:
        commit-message: Update.
        add-options: -A
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.REPO_TOKEN }}
