name: Update

on:
  push:
    branches: 
      - master
  schedule:
    - cron: "0 1 * * *"

jobs:
  dns:
    name: 90DNS
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Create local changes
      run: |
        wget https://gitlab.com/a/90dns/-/raw/master/dnsmasq/dnsmasq.conf -O /tmp/dnsmasq.conf
        sed -i '/^interface.*/d' /tmp/dnsmasq.conf
        sed -i 's/address=\//DOMAIN,/g' /tmp/dnsmasq.conf
        sed -i 's/DOMAIN,\./DOMAIN-SUFFIX,/g' /tmp/dnsmasq.conf
        sed -i 's/\/127.0.0.1/,REJECT/g' /tmp/dnsmasq.conf
        sed -i 's/\/[0-9].*/,DIRECT/g' /tmp/dnsmasq.conf
        grep '.*DIRECT' /tmp/dnsmasq.conf > /tmp/90dns.yml
        grep '.*DIRECT' /tmp/dnsmasq.conf > /tmp/90dns_direct_provider.yml && sed -i "s/^/  - '/g" /tmp/90dns_direct_provider.yml && sed -i "s/$/'/g" /tmp/90dns_direct_provider.yml && sed -i 's/,DIRECT//g' /tmp/90dns_direct_provider.yml
        grep '.*REJECT' /tmp/dnsmasq.conf >> /tmp/90dns.yml
        grep '.*REJECT' /tmp/dnsmasq.conf > /tmp/90dns_reject_provider.yml && sed -i "s/^/  - '/g" /tmp/90dns_reject_provider.yml && sed -i "s/$/'/g" /tmp/90dns_reject_provider.yml && sed -i 's/,REJECT//g' /tmp/90dns_reject_provider.yml
        sed -i '1i\# > 90DNS'  /tmp/90dns.yml
        sed -i '1i\payload:'  /tmp/90dns_direct_provider.yml
        sed -i '1i\payload:'  /tmp/90dns_reject_provider.yml
        cat /tmp/90dns.yml > ./Clash/90dns.yml
        cat /tmp/90dns_direct_provider.yml > ./Clash/90dns_direct_provider.yml
        cat /tmp/90dns_reject_provider.yml > ./Clash/90dns_reject_provider.yml
    - uses: autosuite/autocommit@master
      with:
        commit-message: Update
        add-options: -A
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.REPO_TOKEN }}

  china_ipv4_list:
    name: China IPv4 List
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Create local changes
      run: |
        wget https://raw.githubusercontent.com/17mon/china_ip_list/master/china_ip_list.txt -O ./Surge/IPDB/surge_china_ipv4.txt
    - name: Commit files
      uses: autosuite/autocommit@master
      with:
        commit-message: Update
        add-options: -A
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.REPO_TOKEN }}

  china_ipv6_list:
    name: China IPv6 List
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Create local changes
      run: |
        wget http://ftp.apnic.net/stats/apnic/delegated-apnic-latest -O /tmp/ipv6
        cat /tmp/ipv6 | awk -F '|' '/CN/&&/ipv6/ {print $4 "/" $5}' | cat > ./Surge/IPDB/surge_china_ipv6.txt 
    - name: Commit files
      uses: autosuite/autocommit@master
      with:
        commit-message: Update
        add-options: -A
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.REPO_TOKEN }}

  china_ip_list:
    name: China IP List
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Create local changes
      run: |
        cat ./Surge/IPDB/surge_china_ipv4.txt ./Surge/IPDB/surge_china_ipv6.txt > ./Surge/IPDB/surge_china_ip.txt
        sed -e "s/^/  - '/g" -e "s/$/'/g" -e '1i\payload:' ./Surge/IPDB/surge_china_ipv4.txt > ./Clash/china_ipv4.yml
        sed -e "s/^/  - '/g" -e "s/$/'/g" -e '1i\payload:' ./Surge/IPDB/surge_china_ipv6.txt > ./Clash/china_ipv6.yml
        sed -e "s/^/  - '/g" -e "s/$/'/g" -e '1i\payload:' ./Surge/IPDB/surge_china_ip.txt > ./Clash/china_ip.yml
        wget https://github.com/alecthw/mmdb_china_ip_list/releases/latest/download/china_ip_list.mmdb -O ./Clash/china_ip_list.mmdb
    - name: Commit files
      uses: autosuite/autocommit@master
      with:
        commit-message: Update
        add-options: -A
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.REPO_TOKEN }}

  ublacklist:
    name: uBlacklist
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Create local changes
      run: |
        curl https://raw.githubusercontent.com/cobaltdisco/Google-Chinese-Results-Blocklist/master/uBlacklist_subscription.txt > /tmp/list
        curl https://raw.githubusercontent.com/liubiantao/uBlacklist-Websites/master/uBlacklist.txt >> /tmp/list
        curl https://raw.githubusercontent.com/DivineEngine/uBlacklist/master/blacklist.txt >> /tmp/list
        curl https://raw.githubusercontent.com/YeSilin/uBlacklist/master/list.txt >> /tmp/list
        curl https://raw.githubusercontent.com/teokree/blacklist/master/blacklist.txt >> /tmp/list
        curl https://raw.githubusercontent.com/nonPointer/uBlacklist-Subscription/master/blacklist.txt >> /tmp/list
        cat ./uBlacklist/Extra.txt >> /tmp/list
        sort -u /tmp/list | sed 's/!.*//g' | sed '/^$/d'> uBlacklist/uBlacklist.txt
    - name: Commit files
      uses: autosuite/autocommit@master
      with:
        commit-message: Update
        add-options: -A
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.REPO_TOKEN }}
