name: Update

on:
  push:
    branches: 
      - master
  schedule:
    - cron: "0 1 * * *"

jobs:
  dns:
    name: 90DNS
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Create local changes
      run: |
        curl https://gitlab.com/a/90dns/-/raw/master/dnsmasq/dnsmasq.conf > /tmp/dnsmasq.conf
        sed -i -e '/^interface.*/d' -e 's/address=\//DOMAIN,/g' -e 's/DOMAIN,\./DOMAIN-SUFFIX,/g' -e 's/\/127.0.0.1/,REJECT/g' -e 's/\/[0-9].*/,DIRECT/g' /tmp/dnsmasq.conf
        grep '.*DIRECT' /tmp/dnsmasq.conf > /tmp/90dns.yml
        grep '.*DIRECT' /tmp/dnsmasq.conf | sed -e "s/^/  - '/g" -e "s/$/'/g" -e 's/,DIRECT//g' -e '1i\payload:' > /tmp/90dns_direct_provider.yml
        grep '.*REJECT' /tmp/dnsmasq.conf >> /tmp/90dns.yml
        grep '.*REJECT' /tmp/dnsmasq.conf | sed -e "s/^/  - '/g" -e "s/$/'/g" -e 's/,REJECT//g' -e '1i\payload:' > /tmp/90dns_reject_provider.yml 
        sed -i '1i\# > 90DNS'  /tmp/90dns.yml
        cat /tmp/90dns.yml > ./Clash/90dns.yml
        cat /tmp/90dns_direct_provider.yml > ./Clash/90dns_direct_provider.yml
        cat /tmp/90dns_reject_provider.yml > ./Clash/90dns_reject_provider.yml
    - uses: autosuite/autocommit@master
      with:
        commit-message: Update 90DNS
        add-options: -A
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.REPO_TOKEN }}

  china_ip:
    name: China IP
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Create local changes
      run: |
        curl https://raw.githubusercontent.com/17mon/china_ip_list/master/china_ip_list.txt > ./Surge/IPDB/surge_china_ipv4.txt

        curl http://ftp.apnic.net/stats/apnic/delegated-apnic-latest | awk -F '|' '/CN/&&/ipv6/ {print "[" $4 "]/" $5}' | cat > ./Surge/IPDB/surge_china_ipv6.txt
        
        echo '' > /tmp/blank
        cat ./Surge/IPDB/surge_china_ipv4.txt /tmp/blank ./Surge/IPDB/surge_china_ipv6.txt > ./Surge/IPDB/surge_china_ip.txt
        sed -e "s/^/  - '/g" -e "s/$/'/g" -e '1i\payload:' ./Surge/IPDB/surge_china_ipv4.txt > ./Clash/china_ipv4.yml
        sed -e "s/^/  - '/g" -e "s/$/'/g" -e '1i\payload:' ./Surge/IPDB/surge_china_ipv6.txt > ./Clash/china_ipv6.yml
        sed -e "s/^/  - '/g" -e "s/$/'/g" -e '1i\payload:' ./Surge/IPDB/surge_china_ip.txt > ./Clash/china_ip.yml
        curl https://github.com/alecthw/mmdb_china_ip_list/releases/latest/download/china_ip_list.mmdb -o ./Clash/china_ip_list.mmdb
    - name: Commit files
      uses: autosuite/autocommit@master
      with:
        commit-message: Update China IP
        add-options: -A
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.REPO_TOKEN }}

  ublacklist:
    name: uBlacklist
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Create local changes
      run: |
        curl https://raw.githubusercontent.com/cobaltdisco/Google-Chinese-Results-Blocklist/master/uBlacklist_subscription.txt > /tmp/list
        curl https://raw.githubusercontent.com/liubiantao/uBlacklist-Websites/master/uBlacklist.txt >> /tmp/list
        curl https://raw.githubusercontent.com/DivineEngine/uBlacklist/master/blacklist.txt >> /tmp/list
        curl https://raw.githubusercontent.com/YeSilin/uBlacklist/master/list.txt >> /tmp/list
        curl https://raw.githubusercontent.com/teokree/blacklist/master/blacklist.txt >> /tmp/list
        curl https://raw.githubusercontent.com/nonPointer/uBlacklist-Subscription/master/blacklist.txt >> /tmp/list
        curl https://raw.githubusercontent.com/gyli/Blocklist/master/BLOCKLIST | sed -e 's/^/*:\/\//g' -e 's/$/\/*/g' >> /tmp/list
        curl https://raw.githubusercontent.com/scyrte/uBlacklist-Subscription/master/blacklist.txt | sed -e 's/^/*:\/\//g' -e 's/$/\/*/g' >> /tmp/list
        curl https://raw.githubusercontent.com/yangjingchuang/ublacklist-subscription/master/uBlacklist.txt >> /tmp/list
        cat ./uBlacklist/Extra.txt >> /tmp/list
        sort -u /tmp/list | sed 's/!.*//g' | sed '/^$/d'> uBlacklist/uBlacklist.txt
    - name: Commit files
      uses: autosuite/autocommit@master
      with:
        commit-message: Update uBlacklist
        add-options: -A
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.REPO_TOKEN }}

  QuantumultX:
    name: Quantumult X
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: Get Hostnames
      run: |
        python ./QuantumultX/getHostname.py
    - name: Commit files
      uses: autosuite/autocommit@master
      with:
        commit-message: Update Hostnames
        add-options: -A
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.REPO_TOKEN }}
